import Head from 'next/head'
import styles from '../styles/Home.module.css'

export async function getServerSideProps(){
  const res = await fetch('https://3000-codewithsno-dailyissues-4z0lo7u8fld.ws-us43.gitpod.io/api/issues')
  const data = res.json()

  return { props: {data}}
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Daily Issues
        </h1>
        <p>Name: {data.name}</p>       
        <p>Author: {data.author}</p>       
        <p>Labels: {data.labels.join(",")}</p>       
        <p>URL: {data.url}</p>       
      </main>

      <footer className={styles.footer}>
          Powered by Open Source
      </footer>
    </div>
  )
}
